### ISSUE TITLE
Roadmap to release

### ISSUE THREAD

**Issue by zetachang** [zetachang/react.rb#1]
- [x] Add test for state should be original object
- [x] props should remain the same
- [x] ~~set_state callback spec~~ actually hard to write. 
- [ ] Compatible of DSL with original one
- [ ] Add test for todos
- [x] ~~initial state rely on props?~~ [considered as an anti-pattern](http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html)
- [ ] select should allow array (http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html)
- [x] Class name
- [x] Mixins
- [x] alias_native event key code.... etc
- [x] Upgrade to opal 0.7.0
- [x] Write README...
- [ ] Coverage of APIs, refer to #2

**Comment by ajjahn** [comment]
@catmando Same for this one...

> Of the unchecked items in this list, do you know if any have been implemented?

**Comment by catmando** [comment]
This issue was moved to reactrb/reactrb#1
